config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'

  resources :subscribers, only: [:create]

  namespace :admin do
    root to: 'base#index'
    resources :prizes
    resources :prize_conditions
    resources :sessions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manage_matched_prize_conditions.rb
class ManageMatchedPrizeConditions

  def initialize(subscription_number:)
    @prize_condition_checker = PrizeConditionsChecker.new(subscription_number: subscription_number)
  end

  def first_condition
    all_conditions = @prize_condition_checker.get_all_match_conditions
    gets_first_condition_overlaps_others(all_conditions)
  end

  private
  def gets_first_condition_overlaps_others(all_conditions)
    prize_condition = all_conditions.shift
    PrizeConditionRepository.set_overlapped(all_conditions)
    PrizeConditionRepository.set_not_overlapped([prize_condition])
    prize_condition
  end

end

app/models/matched_prize_conditions.rb
class MatchedPrizeConditions

  def initialize(subscription_number:)
    @prize_condition_checker = RulePrizeConditionsChecker.new(subscription_number: subscription_number)
  end

  def first_condition
    all_conditions = @prize_condition_checker.get_all_match_conditions
    gets_first_condition_overlaps_others(all_conditions)
  end

  def gets_first_condition_overlaps_others(all_conditions)
    prize_condition = all_conditions.shift
    PrizeConditionRepository.set_overlapped(all_conditions)
    PrizeConditionRepository.set_not_overlapped([prize_condition])
    prize_condition
  end

end

app/models/prize.rb
class Prize < ApplicationRecord

  def decrease_quantity!
    self.quantity -= 1
    self.save
  end

  def has_conditions?
    PrizeCondition.where(prize_id: self.id).any?
  end
end

app/models/prize_condition.rb
class PrizeCondition < ApplicationRecord
  OPERATORS_LIST = [["Equal","=="],["Greater than", ">"],["Multiple of", "multiple_of?"],["Smaller than", "<"]]
  belongs_to :prize

  def self.operators_list
    OPERATORS_LIST
  end

  def prize_name
    self.prize.name
  end

  def matches_all_rules?(number)
    self.rules.all?{ | rule| check_rule(number, rule) }
  end

  def check_rule(number, rule)
    number.send(rule["operator"], rule["number"].to_i)
  end

end

app/models/prize_conditions_checker.rb
class PrizeConditionsChecker

  def initialize(subscription_number:)
    @subscription_number = subscription_number
    @conditions = PrizeConditionRepository.with_prize_available
  end

  def get_all_match_conditions
    matched = @conditions.select{ |condition| condition.matches_all_rules?(@subscription_number) }
    matched.unshift(get_overlapped_conditions).flatten.compact
  end

  private
  def get_overlapped_conditions
    PrizeConditionRepository.get_overlapped
  end

end

app/models/rule_prize_conditions_checker.rb
class RulePrizeConditionsChecker

  def initialize(subscription_number:)
    @subscription_number = subscription_number
    @conditions = PrizeConditionRepository.with_prize_available
  end

  def get_all_match_conditions
    matched = @conditions.select{ |condition| RulesChecker.new(subscriber_number: @subscription_number, rules: condition.rules).matches_all_rules? }
    matched.unshift(get_overlapped_condition).flatten.compact
  end

  private
  def get_overlapped_condition
    PrizeConditionRepository.get_overlapped
  end

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :prize, optional: true

  def self.subscribe!(email)
    check_subscription!(email)
    Subscription.create(last_subscription: DateTime.now, email: email)
  end

  def self.check_subscription!(email)
    raise SubscriptionLimitError.new("Sorry, only one subscription per day :(") if self.any_subscription_today?(email)
  end

  def self.any_subscription_today?(email)
    self.where(email: email, last_subscription: Date.today.beginning_of_day..Date.today.end_of_day).any?
  end

  def receive_prize!(prize)
    self.update_attribute(:prize, prize)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, uniqueness: true

   def self.login!(username:, password:)
    user = User.find_by!(username: username)
    raise ActiveRecord::RecordNotFound unless user.authenticate(password)
    user.update_attribute(:session_token, SecureRandom.urlsafe_base64)
    user
  end
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    include SessionsHelper

    before_action :load_session!

    def index
      @prize_conditions = ListPrizeConditions.new.execute
      @prizes = ListPrizes.new.execute
    end

  end
end

app/controllers/admin/prize_conditions_controller.rb
module Admin
  class PrizeConditionsController < BaseController

    before_action :find_prize_condition, only: [:edit, :update, :destroy]

    def index
      @prize_conditions = ListPrizeConditions.new.execute
    end

    def create
      @prize_condition = PrizeCondition.create(prize_condition_params)
      flash[:success] = 'Prize condition created'
      redirect_to admin_root_path
    end

    def new
      @prize_condition = PrizeCondition.new
      @prizes = ListPrizes.new.execute
      @prize = Prize.new
      @operators_list = PrizeCondition.operators_list
    end

    def edit
      @prizes = ListPrizes.new.execute
      @prize = @prize_condition.prize
      @operators_list = PrizeCondition.operators_list
    end

    def update
      @prize_condition.update_attributes(prize_condition_params)
      flash[:success] = 'Prize condition updated'
      redirect_to admin_root_path
    end

    def destroy
      @prize_condition.destroy
      flash[:success] = 'Prize condition deleted'
      redirect_to admin_root_path
    end

    private
    def find_prize_condition
      @prize_condition = PrizeCondition.find(params[:id])
    end

    def prize_condition_params
      params.require(:prize_condition).permit(:name, :prize_id, rules: [:operator, :number])
    end

  end
end

app/controllers/admin/prizes_controller.rb
module Admin
  class PrizesController < BaseController

    before_action :find_prize, only: [:edit, :update, :destroy]

    def index
      @prizes = ListPrizes.new.execute
    end

    def create
      Prize.create(prize_params)
      flash[:success] = 'Prize created'
      redirect_to admin_root_path
    end

    def new
      @prize = Prize.new
    end

    def edit
    end

    def update
      @prize.update_attributes(prize_params)
      flash[:success] = 'Prize updated'
      redirect_to admin_root_path
    end

    def destroy
      @prize.destroy
      flash[:success] = 'Prize deleted'
      redirect_to admin_root_path
    end

    private
    def find_prize
      @prize = Prize.find(params[:id])
    end

    def prize_params
      params.require(:prize).permit(:name, :quantity)
    end

  end
end

app/controllers/admin/sessions_controller.rb
module Admin
  class SessionsController < BaseController
    skip_before_action :load_session!

    def new
    end

    def create
      begin
        user = User.login!(username: params[:email].downcase, password: params[:password])
        log_in user
        redirect_to admin_root_path
      rescue ActiveRecord::RecordNotFound
        flash.now[:danger] = 'Invalid email/password combination'
        render action: :new
      end
    end

    def destroy
      log_out
      redirect_to root_url
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

  def create
    @error = nil
    begin
      subscription = CreateSubscription.new(email: params[:email]).execute
      ProcessPrize.new(subscription: subscription).execute
      @prize = subscription.prize
    rescue SubscriptionLimitError => e
      @error = e
      render "error"
    end
  end

end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper

  def log_in(user)
    session[:session_token] = user.session_token
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:session_token)
    @current_user = nil
  end

  def load_session!
    redirect_to new_admin_session_path unless logged_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/base/index.html.erb
<main class="container mt-5">
  <h1>Admin</h1>
  <hr>
  <%= render partial: 'admin/prizes/list'  %>
  <hr>
  <%= render partial: 'admin/prize_conditions/list'  %>
</main>

app/views/admin/prize_conditions/_form.html.erb
<%= form_with model: [:admin, @prize_condition] do | form | %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label for="name"">Name</label>
        <%= form.text_field :name, class: "form-control", required: true %>
      </div>
      <div class="form-group">
        <label for="name"">Prize</label>
        <%= form.select :prize_id, options_from_collection_for_select(@prizes, :id, :name, @prize.id), {}, class: "form-control", prompt: "Select the prize", required: true  %>
      </div>
      <div class="row mt-4">
        <div class="col-md-6">
          <h4>Rules</h4>
        </div>
        <div class="col-md-6">
          <a href="javascript:;" onclick="addRule()" id="add-rule" class="btn btn-info btn-sm float-right">Add other rule</a>
        </div>
      </div>
      <div id="all-rules-form">
        <% if @prize_condition.rules.blank? %>
          <%= render partial: "rules_form", locals: { rule: {"number": "", operator: ""} } %>
        <% else %>
          <% @prize_condition.rules.each do | rule | %>
            <%= render partial: "rules_form", locals: { rule: rule } %>
          <% end %>
        <% end %>
      </div>
      <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<%= javascript_include_tag 'form_rules' %>

app/views/admin/prize_conditions/_list.html.erb
<div class="row">
  <div class="col-sm-6 bd-content">
    <h2 class="bd-title">List of prize conditions</h2>
  </div>
  <div class="col-sm-6 ">
    <%= link_to "Create new condition", new_admin_prize_condition_path, class: "btn btn-primary float-right" %>
  </div>
</div>
<div class="row mt-3">
  <div class="col-sm-12">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Creation date</th>
          <th scope="col">Prize</th>
          <th scope="col">Edit</th>
          <th scope="col">Destroy</th>
        </tr>
      </thead>
      <tbody>
        <% @prize_conditions.each do | prize_condition | %>
          <tr>
            <td><%= prize_condition.name %></td>
            <td><%= prize_condition.created_at %></td>
            <td><%= prize_condition.prize_name %></td>
            <td><%= link_to "Edit", edit_admin_prize_condition_path(prize_condition.id) %></td>
            <td><%= link_to "X", admin_prize_condition_path(prize_condition.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        <% if @prize_conditions.empty? %>
        <tr >
          <td colspan="5">No prize conditions created yet</td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/prize_conditions/_rules_form.html.erb
<div id="rule-form" class="form-group">
  <div class="row">
    <div class="col-md-5">
      <label for="operator">Operator</label>
      <%= select_tag "prize_condition[rules[][operator]]", options_for_select(@operators_list, rule["operator"]), class: "form-control", required: true, prompt: "Select the operator" %>
      <small id="emailHelp" class="form-text text-muted">Define if the subscriber number is</small>
    </div>
    <div class="col-md-5">
      <label for="number">Number</label>
      <%= number_field_tag "prize_condition[rules[][number]]", rule["number"], class: "form-control", required: true %>
      <small id="emailHelp" class="form-text text-muted">Number to compare</small>
    </div>
    <div class="col-md-2">
      <label for="remove"></label>
      <a href="javascript:;" onclick="removeRule(this)" id="add-rule" class="mt-2 btn btn-danger btn-sm float-right">Remove</a>
    </div>
  </div>
</div>

app/views/admin/prize_conditions/edit.html.erb
<div class="row">
  <div class="col-md-5">
    <h2>Edit the prize condition</h2>
  </div>
  <div class="col-md-1">
    <%= link_to "Back", admin_root_path, class: "btn btn-secondary" %>
  </div>
</div>
<%= render "form" %>

app/views/admin/prize_conditions/index.html.erb
<main class="container mt-5">
  <%= render partial: 'admin/prize_conditions/list'  %>
</main>

app/views/admin/prize_conditions/new.html.erb
<div class="row">
  <div class="col-md-5">
    <h2>Create new prize condition</h2>
  </div>
  <div class="col-md-2">
    <%= link_to "Back", admin_root_path, class: "btn btn-secondary" %>
  </div>
</div>
<%= render "form" %>

app/views/admin/prizes/_form.html.erb
<%= form_with model: [:admin, @prize] do | form | %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label for="name"">Name</label>
        <%= form.text_field :name, class: "form-control", required: true %>
      </div>
      <div class="form-group">
        <label for="quantity">Quantity</label>
        <%= form.number_field :quantity, class: "form-control", required: true %>
      </div>
      <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/prizes/_list.html.erb
<div class="row">
  <div class="col-sm-6 bd-content">
    <h2 class="bd-title">List of prizes</h2>
  </div>
  <div class="col-sm-6">
    <%= link_to "Create new prize", new_admin_prize_path, class: "btn btn-primary float-right" %>
  </div>
</div>
<div class="row mt-3">
  <div class="col-sm-12">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Quantity Left</th>
          <th scope="col">Edit</th>
          <th scope="col">Destroy</th>
        </tr>
      </thead>
      <tbody>
        <% @prizes.each do | prize | %>
          <tr>
            <th scope="row"><%= prize.id %></th>
            <td><%= prize.name %></td>
            <td><%= prize.quantity %></td>
            <td><%= link_to "Edit", edit_admin_prize_path(prize.id) %></td>
            <td>
              <% unless prize.has_conditions? %>
                <%= link_to "X", admin_prize_path(prize.id), method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </td>
          </tr>
        <% end %>
        <% if @prizes.empty? %>
        <tr >
          <td colspan="5">No prizes created yet</td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/prizes/edit.html.erb
<div class="row">
  <div class="col-md-5">
    <h2>Edit the prize</h2>
  </div>
  <div class="col-md-1">
    <%= link_to "Back", admin_root_path, class: "btn btn-secondary" %>
  </div>
</div>
<%= render "form" %>

app/views/admin/prizes/index.html.erb
<main class="container mt-5">
  <%= render partial: 'admin/prizes/list'  %>
</main>

app/views/admin/prizes/new.html.erb
<div class="row">
  <div class="col-md-5">
    <h2>Create new prize</h2>
  </div>
  <div class="col-md-2">
    <%= link_to "Back", admin_root_path, class: "btn btn-secondary" %>
  </div>
</div>
<%= render "form" %>

app/views/home/index.html.erb
<main role="main">
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h2 class="display-4">Web Prizes</h2>
      <p>Subscribe to our store and get info about new products. You can win several prizes!</p>
      <%= render partial: "subscribers/form" %>
    </div>
  </div>
  <div id="alert-area"></div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebPrizes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "Web Prizes", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Admin", admin_root_path, class: "nav-link" %>
        </li>
      </ul>
      <% if logged_in? %>
        <%= link_to 'Log out', admin_session_path(current_user.id), method: :delete, class: "btn btn-outline-secondary", data: { confirm: 'Are you sure?' } %>
      <% end %>
    </nav>
    <main class="container mt-5">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/subscribers/_error.html.erb
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading">Sorry!</h4>
  <p><%= @error %></p>
</div>

app/views/subscribers/_form.html.erb
<%= form_tag subscribers_path, remote: true do %>
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-1 col-form-label">Email</label>
    <div class="col-sm-4">
      <%= email_field_tag :email, "", class: "form-control", placeholder: "joe@email.com" %>
    </div>
    <div class="col-sm-4">
      <%= submit_tag "Subscribe", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/subscribers/_subscribed.html.erb
<div class="alert alert-info" role="alert">
  <h4 class="alert-heading">Subscribed!</h4>
  <p>You are now subscribed to receive our news</p>
</div>

app/views/subscribers/_won_prize.html.erb
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Congratulations!</h4>
  <p>You won the prize: <b><%= prize.name %></b></p>
</div>

app/views/subscribers/create.js.erb
<% if @prize.present? %>
  document.getElementById("alert-area").innerHTML  = "<%= j(render partial: 'subscribers/won_prize', locals: { prize: @prize}) %>"
<% else %>
  document.getElementById("alert-area").innerHTML =  "<%= j(render partial: 'subscribers/subscribed') %>"
<% end %>

app/views/subscribers/error.js.erb
document.getElementById("alert-area").innerHTML = "<%= j(render partial: 'subscribers/error') %>"